//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinTimeWebsite.CoinTimeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoinTimeService.ICTSerrvice")]
    public interface ICTSerrvice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTSerrvice/GetCoinbaseExchangeRate", ReplyAction="http://tempuri.org/ICTSerrvice/GetCoinbaseExchangeRateResponse")]
        string GetCoinbaseExchangeRate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTSerrvice/GetCoinbaseExchangeRate", ReplyAction="http://tempuri.org/ICTSerrvice/GetCoinbaseExchangeRateResponse")]
        System.Threading.Tasks.Task<string> GetCoinbaseExchangeRateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTSerrviceChannel : CoinTimeWebsite.CoinTimeService.ICTSerrvice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTSerrviceClient : System.ServiceModel.ClientBase<CoinTimeWebsite.CoinTimeService.ICTSerrvice>, CoinTimeWebsite.CoinTimeService.ICTSerrvice {
        
        public CTSerrviceClient() {
        }
        
        public CTSerrviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTSerrviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTSerrviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTSerrviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCoinbaseExchangeRate() {
            return base.Channel.GetCoinbaseExchangeRate();
        }
        
        public System.Threading.Tasks.Task<string> GetCoinbaseExchangeRateAsync() {
            return base.Channel.GetCoinbaseExchangeRateAsync();
        }
    }
}
